version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - "type:maintenance"
      - "area:security"
    commit-message:
      prefix: "chore"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    labels:
      - "type:maintenance"
      - "area:security"
    commit-message:
      prefix: "chore"
    groups:
      github-actions:
        patterns:
          - "*"
