import type { FdOrgInputNode } from "../org-chart-types.js";

/**
 * Real-world FDIC Division of Insurance and Research org chart, transcribed
 * from the public chart for fixture coverage. Exercises:
 *
 * - Mixed branch + leaf siblings at the same level (so the multi-column leaf
 *   flow has somewhere to demonstrate itself).
 * - Several acting assignments (actingMeta with official source status).
 * - Two real vacancies under Daniel Hoople, exercising the low-priority sort
 *   tier end-to-end.
 * - "Regions" and "Center for Financial Research" rendered as `unit` parents
 *   that group leaf people underneath them.
 */
export const dirOrgFixture: FdOrgInputNode[] = [
  {
    id: "dir",
    label: "Division of Insurance and Research",
    title: "Division",
    nodeType: "unit",
    sourceStatus: "official",
    sourceMeta: {
      source: "fixture",
      label: "DIR public org chart",
      fetchedAt: "2026-05-08",
    },
  },
  {
    id: "felton",
    parentId: "dir",
    label: "Andrew Felton",
    title: "Director",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Andrew Felton" },
  },

  // Deposit Insurance & Risk Analysis branch
  {
    id: "mihalik",
    parentId: "felton",
    label: "Ashley Mihalik",
    title: "Deputy Director, Deposit Insurance & Risk Analysis",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Ashley Mihalik" },
  },
  {
    id: "hoople",
    parentId: "mihalik",
    label: "Daniel Hoople",
    title: "Associate Director, Financial Risk Management",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Daniel Hoople" },
  },
  {
    id: "garnett",
    parentId: "hoople",
    label: "Edward Garnett",
    title: "Chief, Large Bank Pricing Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Edward Garnett" },
  },
  {
    id: "vac-fund-pricing",
    parentId: "hoople",
    label: "Vacant",
    title: "Chief, Fund Analysis & Pricing Section",
    nodeType: "vacancy",
    sourceStatus: "official",
  },
  {
    id: "vac-banking-policy",
    parentId: "hoople",
    label: "Vacant",
    title: "Chief, Banking & Regulatory Policy Section",
    nodeType: "vacancy",
    sourceStatus: "official",
  },
  {
    id: "shah",
    parentId: "mihalik",
    label: "Shilpa Shah",
    title: "Associate Director, International Affairs",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Shilpa Shah" },
  },
  {
    id: "singer",
    parentId: "mihalik",
    label: "Ryan Singer",
    title: "Associate Director, National & Regional Risk Analysis",
    nodeType: "person",
    sourceStatus: "official",
    actingMeta: {
      assignmentLabel: "Acting Associate Director",
      sourceLabel: "HR acting roster",
    },
    person: { displayName: "Ryan Singer" },
  },
  {
    id: "presley-nelson",
    parentId: "singer",
    label: "James Presley-Nelson",
    title: "Chief, Financial Analysis Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "James Presley-Nelson" },
  },
  {
    id: "patel",
    parentId: "singer",
    label: "Krishna Patel",
    title: "Chief, Economic Analysis Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Krishna Patel" },
  },
  {
    id: "regions",
    parentId: "singer",
    label: "Regions",
    title: "Regional Manager group",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "dichiara",
    parentId: "regions",
    label: "Robert DiChiara",
    title: "Regional Manager, New York/Boston",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Robert DiChiara" },
  },
  {
    id: "robbins",
    parentId: "regions",
    label: "Eric Robbins",
    title: "Regional Manager, Chicago",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Eric Robbins" },
  },
  {
    id: "sims",
    parentId: "regions",
    label: "Ronald Sims",
    title: "Regional Manager, Atlanta",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Ronald Sims" },
  },
  {
    id: "cofer",
    parentId: "regions",
    label: "Richard Cofer",
    title: "Regional Manager, Kansas City",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Richard Cofer" },
  },
  {
    id: "mcgee",
    parentId: "regions",
    label: "John McGee",
    title: "Regional Manager, San Francisco",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "John McGee" },
  },
  {
    id: "kiser",
    parentId: "regions",
    label: "Stephen Kiser",
    title: "Regional Manager, Dallas",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Stephen Kiser" },
  },

  // Data & Resource Management branch
  {
    id: "deaton",
    parentId: "felton",
    label: "Alan Deaton",
    title: "Deputy Director, Data & Resource Management",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Alan Deaton" },
  },
  {
    id: "oliver",
    parentId: "deaton",
    label: "Eboni Oliver",
    title: "Special Assistant",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Eboni Oliver" },
  },
  {
    id: "marshall",
    parentId: "deaton",
    label: "Alexander Marshall",
    title: "Associate Director, Data, Analytics & Statistics Branch",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Alexander Marshall" },
  },
  {
    id: "peery",
    parentId: "marshall",
    label: "Troy Peery",
    title: "Chief, Large Data Management Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Troy Peery" },
  },
  {
    id: "iluyomade",
    parentId: "marshall",
    label: "Kete Iluyomade",
    title: "Chief, Data Collection & Analysis Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Kete Iluyomade" },
  },
  {
    id: "boggan",
    parentId: "marshall",
    label: "Chad Boggan",
    title: "Chief, Data Strategy Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Chad Boggan" },
  },
  {
    id: "allagh",
    parentId: "deaton",
    label: "Neeta Allagh",
    title: "Assistant Director, Planning & Resource Management Branch",
    nodeType: "person",
    sourceStatus: "official",
    actingMeta: {
      assignmentLabel: "Acting Assistant Director",
      sourceLabel: "HR acting roster",
    },
    person: { displayName: "Neeta Allagh" },
  },
  {
    id: "vogel",
    parentId: "allagh",
    label: "Donna Vogel",
    title: "Chief, Publications & IT Operations Section",
    nodeType: "person",
    sourceStatus: "official",
    actingMeta: {
      assignmentLabel: "Acting Chief",
      sourceLabel: "HR acting roster",
    },
    person: { displayName: "Donna Vogel" },
  },
  {
    id: "sothoron",
    parentId: "allagh",
    label: "Arlinda Sothoron",
    title: "Chief, Strategic Planning & Internal Controls Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Arlinda Sothoron" },
  },

  // Research & Regulatory Analysis branch
  {
    id: "pogach",
    parentId: "felton",
    label: "Jonathan Pogach",
    title: "Deputy Director, Research & Regulatory Analysis",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Jonathan Pogach" },
  },
  {
    id: "nguyen",
    parentId: "pogach",
    label: "Daniel Nguyen",
    title: "Chief, Regulatory Analysis Section",
    nodeType: "person",
    sourceStatus: "official",
    actingMeta: {
      assignmentLabel: "Acting Chief",
      sourceLabel: "HR acting roster",
    },
    person: { displayName: "Daniel Nguyen" },
  },
  {
    id: "cfr",
    parentId: "pogach",
    label: "Center for Financial Research",
    title: "Center",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "chu",
    parentId: "cfr",
    label: "Karyen Chu",
    title: "Chief, Banking Research Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Karyen Chu" },
  },
  {
    id: "ufier",
    parentId: "cfr",
    label: "Alexander Ufier",
    title: "Chief, Quantitative Risk Analysis Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Alexander Ufier" },
  },
  {
    id: "kisin",
    parentId: "cfr",
    label: "Roni Kisin",
    title: "Chief, Financial Modeling & Research Section",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Roni Kisin" },
  },
];
