import type { FdOrgInputNode } from "../org-chart-types.js";

export const fdicShapeOrgFixture: FdOrgInputNode[] = [
  {
    id: "fdic",
    label: "Federal Deposit Insurance Corporation",
    title: "Agency",
    nodeType: "unit",
    sourceStatus: "official",
    sourceMeta: { source: "fixture", label: "FDIC-shaped fixture", fetchedAt: "2026-05-08" },
  },
  {
    id: "division-depositor",
    parentId: "fdic",
    label: "Division of Depositor and Consumer Protection",
    title: "Division",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "division-risk",
    parentId: "fdic",
    label: "Division of Risk Management Supervision",
    title: "Division",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "division-resolutions",
    parentId: "fdic",
    label: "Division of Resolutions and Receiverships",
    title: "Division",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "office-consumer-response",
    parentId: "division-depositor",
    label: "Consumer Response Center",
    title: "Office",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "office-supervision-policy",
    parentId: "division-risk",
    label: "Supervision Policy",
    title: "Office",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "office-receivership-ops",
    parentId: "division-resolutions",
    label: "Receivership Operations",
    title: "Office",
    nodeType: "unit",
    sourceStatus: "official",
  },
  {
    id: "pos-consumer-director",
    parentId: "office-consumer-response",
    label: "Director",
    title: "Consumer Response Center",
    nodeType: "position",
    sourceStatus: "official",
  },
  {
    id: "person-morgan",
    parentId: "pos-consumer-director",
    label: "Morgan Lee",
    title: "Director",
    nodeType: "person",
    sourceStatus: "official",
    person: { displayName: "Morgan Lee" },
  },
  {
    id: "pos-policy-manager",
    parentId: "office-supervision-policy",
    label: "Policy Manager",
    title: "Supervision Policy",
    nodeType: "position",
    sourceStatus: "official",
  },
  {
    id: "vac-policy-manager",
    parentId: "pos-policy-manager",
    label: "Vacant",
    title: "Policy Manager",
    nodeType: "vacancy",
    sourceStatus: "official",
  },
  {
    id: "pos-ops-lead",
    parentId: "office-receivership-ops",
    label: "Operations Lead",
    title: "Receivership Operations",
    nodeType: "position",
    sourceStatus: "official",
  },
  {
    id: "person-jordan",
    parentId: "pos-ops-lead",
    label: "Jordan Patel",
    title: "Acting Operations Lead",
    nodeType: "person",
    sourceStatus: "override",
    actingMeta: { effectiveStart: "2026-04-01", sourceLabel: "Editorial override" },
    overrideMeta: { label: "Temporary assignment", updatedAt: "2026-04-01" },
  },
];
