#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import {
  componentInventory,
  componentIndexPath as docsComponentsIndexPath,
  componentsPackagePath,
  componentSourceText,
  docsNavGeneratedPath,
  docsPathFor,
  ensureDir,
  extractStaticProperties,
  inferStorybookControl,
  kebabToCamel,
  loadApiMetadata,
  registerAllComponents,
  registerExportComponents,
  registerRoot,
  standaloneDocComponents,
  storybookGeneratedPath,
  symbolExportComponents,
  tsupConfigPath,
  writeText,
  componentsIndexPath as packageComponentsIndexPath,
} from "./lib.mjs";

const GENERATED_HEADER = "This file is generated by `npm run sync:components`.";
const API_START = "<!-- GENERATED_COMPONENT_API:START -->";
const API_END = "<!-- GENERATED_COMPONENT_API:END -->";
const DOCS_CATEGORY_METADATA = [
  {
    key: "forms-input",
    title: "Forms & Input",
    description:
      "Data-entry controls and composition helpers for labels, grouping, validation, and supporting guidance.",
  },
  {
    key: "actions-navigation",
    title: "Actions & Navigation",
    description:
      "Controls and navigation patterns that trigger actions, expose destinations, or move people through flows.",
  },
  {
    key: "feedback-status",
    title: "Feedback & Status",
    description:
      "Components that communicate status, lightweight emphasis, selection context, or supporting state.",
  },
  {
    key: "layout-shell",
    title: "Layout & Shell",
    description:
      "Shell-level and structural components for headers, drawers, search surfaces, and grouped layout treatments.",
  },
  {
    key: "visual-media",
    title: "Visual & Media",
    description:
      "Icons and visual primitives that support other components and layouts without becoming full authored-content patterns.",
  },
];

const apiMetadata = loadApiMetadata();

function formatLiteral(value) {
  if (value === undefined || value === null) return "`undefined`";
  if (typeof value === "string") return `\`${value}\``;
  if (typeof value === "boolean" || typeof value === "number") {
    return `\`${String(value)}\``;
  }

  return `\`${String(value)}\``;
}

function sortComponentsForDocs(components) {
  return [...components].sort((left, right) => {
    const orderDelta = (left.docs.order ?? Number.MAX_SAFE_INTEGER) -
      (right.docs.order ?? Number.MAX_SAFE_INTEGER);

    if (orderDelta !== 0) {
      return orderDelta;
    }

    return left.docs.title.localeCompare(right.docs.title);
  });
}

function groupStandaloneComponentsForDocs() {
  return DOCS_CATEGORY_METADATA.map((category) => ({
    ...category,
    components: sortComponentsForDocs(
      standaloneDocComponents.filter(
        (component) => component.docs.category === category.key,
      ),
    ),
  })).filter((category) => category.components.length > 0);
}

function generateComponentsIndex() {
  const docsCategories = groupStandaloneComponentsForDocs();
  const categoryCards = docsCategories
    .map(
      (category) => `  <div class="fdic-card">
    <span class="fdic-eyebrow">${category.title}</span>
    <h3>${category.components.map((component) => component.docs.title).join(", ")}</h3>
    <p>${category.description}</p>
  </div>`,
    )
    .join("\n");
  const featuredSections = docsCategories
    .map(
      (category) => `### ${category.title}

${category.components
  .map((component) => {
    const description = component.docs.kind === "supporting-standalone"
      ? `documents the supporting primitive contract for ${component.docs.title.toLowerCase()}.`
      : `documents ${component.docs.title.toLowerCase()} usage, constraints, and accessibility guidance.`;

    return `- [${component.docs.title}](./${component.docs.slug}) ${description}`;
  })
  .join("\n")}`,
    )
    .join("\n\n");

  return `# Components

The components section documents the reusable building blocks and authored-content patterns in the FDIC design system.

<div class="fdic-foundation-intro">
  <span class="fdic-eyebrow">Component overview</span>
  <p>Use this section for implementation guidance, usage constraints, accessibility notes, and examples. Foundations explain the underlying rules; components show how those rules are applied in real interfaces and real content.</p>
</div>

## Current component groups

<div class="fdic-card-grid">
${categoryCards}
  <div class="fdic-card">
    <span class="fdic-eyebrow">Authored content</span>
    <h3>Prose</h3>
    <p>The <code>.prose</code> topic covers long-form content styling, document navigation, references, and supporting patterns for articles, policy content, and technical guidance.</p>
  </div>
</div>

These docs group public components by the job they do in an interface. The underlying implementation taxonomy still distinguishes first-class components from supporting primitives for export and composition rules.

Embedded-only supporting primitives such as <code>fd-menu-item</code> and <code>fd-option</code> are documented inside their parent component pages instead of appearing as top-level entries. Internal-only scaffolding primitives such as <code>fd-placeholder</code> are not part of the public component inventory.

## Featured topics

- [Prose](./prose) explains the \`.prose\` container, its boundary with Typography, and the specialized pages for callouts, tables, code blocks, references, disclosure patterns, and progress indicators.
${featuredSections}
`;
}

function generateDocsNavigation() {
  const groupedItems = groupStandaloneComponentsForDocs()
    .map((category) => {
      const items = category.components
        .map(
          (component) =>
            `      { text: "${component.docs.title}", link: "/components/${component.docs.slug}" }`,
        )
        .join(",\n");

      return `  {
    text: "${category.title}",
    items: [
${items}
    ]
  }`;
    })
    .join(",\n");

  return `// ${GENERATED_HEADER}
export const componentSidebarGroups = [
${groupedItems}
];
`;
}

function generateComponentsIndexTs() {
  const classExports = symbolExportComponents
    .filter((component) => component.tagName !== "fd-placeholder")
    .map(
      (component) =>
        `export { ${component.className} } from "./components/${component.sourceFile.replace(/\.ts$/, ".js")}";`,
    )
    .join("\n");

  const typeExports = symbolExportComponents
    .filter((component) => component.typeExports.length > 0)
    .map((component) => {
      const exportsValue = component.typeExports.join(", ");
      return `export type { ${exportsValue} } from "./components/${component.sourceFile.replace(/\.ts$/, ".js")}";`;
    })
    .join("\n");

  return `// ${GENERATED_HEADER}
import "./global.js";

// --- Component classes ---
${classExports}

// --- Public types ---
${typeExports}
export type { Placement } from "./components/placement.js";
export type {
  FdActionDetail,
  FdCheckboxGroupChangeDetail,
  FdMenuItemSelectDetail,
  FdMenuOpenChangeDetail,
  FdOpenChangeDetail,
  FdRadioGroupChangeDetail,
  FdSelectorChangeDetail,
  FdSelectorOpenChangeDetail,
  FdSplitButtonActionDetail,
  FdSplitButtonOpenChangeDetail,
  FdValueChangeDetail,
  FdValuesChangeDetail,
} from "./public-events.js";

// --- Icon registry ---
export { iconRegistry } from "./icons/registry.js";
`;
}

function generateRegisterFile(component) {
  const dependencyLines = component.register.dependencies
    .map((dependency) => {
      const dependencyComponent = componentInventory.find(
        (candidate) => candidate.tagName === dependency,
      );

      return `import { ${dependencyComponent.className} } from "../components/${dependencyComponent.sourceFile.replace(/\.ts$/, ".js")}";`;
    })
    .join("\n");

  const dependencyDefinitions = component.register.dependencies
    .map(
      (dependency) => `if (!customElements.get("${dependency}")) {
  customElements.define("${dependency}", ${componentInventory.find((candidate) => candidate.tagName === dependency).className});
}`,
    )
    .join("\n\n");

  return `// ${GENERATED_HEADER}
import { ${component.className} } from "../components/${component.sourceFile.replace(/\.ts$/, ".js")}";
${dependencyLines ? `${dependencyLines}\n` : ""}
${dependencyDefinitions ? `${dependencyDefinitions}\n\n` : ""}if (!customElements.get("${component.tagName}")) {
  customElements.define("${component.tagName}", ${component.className});
}
`;
}

function generateRegisterAllFile() {
  const importLines = registerAllComponents
    .map(
      (component) =>
        `import "./${component.tagName}.js";`,
    )
    .join("\n");

  return `/**
 * ${GENERATED_HEADER}
 *
 * Convenience entry point — registers all public components and icons.
 *
 * Usage:
 * \`\`\`ts
 * import "@fdic-ds/components/register-all";
 * \`\`\`
 */
${importLines}
import "../icons/phosphor-regular.js";
`;
}

function generateTsupConfig() {
  const symbolEntries = symbolExportComponents
    .map(
      (component) =>
        `    "components/${component.tagName}": "src/components/${component.sourceFile}",`,
    )
    .join("\n");
  const registerEntries = registerExportComponents
    .map(
      (component) =>
        `    "register/${component.tagName}": "src/register/${component.sourceFile}",`,
    )
    .join("\n");

  return `import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    // Root entry (side-effect-free)
    index: "src/index.ts",
    "public-events": "src/public-events.ts",

    // Per-component symbol exports
${symbolEntries}

    // Registration entry points
    "register/register-all": "src/register/register-all.ts",
${registerEntries}

    // Icon packs
    "icons/phosphor-regular": "src/icons/phosphor-regular.ts",
  },
  format: ["esm"],
  dts: true,
  clean: true,
  splitting: true,
});
`;
}

function generatePackageExports(packageJson) {
  const exportsMap = {
    ".": {
      types: "./dist/index.d.ts",
      import: "./dist/index.js",
    },
    "./public-events": {
      types: "./dist/public-events.d.ts",
      import: "./dist/public-events.js",
    },
    "./register-all": {
      types: "./dist/register/register-all.d.ts",
      import: "./dist/register/register-all.js",
    },
    "./register/*": {
      types: "./dist/register/*.d.ts",
      import: "./dist/register/*.js",
    },
  };

  for (const component of symbolExportComponents) {
    exportsMap[`./${component.tagName}`] = {
      types: `./dist/components/${component.tagName}.d.ts`,
      import: `./dist/components/${component.tagName}.js`,
    };
  }

  exportsMap["./icons/phosphor-regular"] = {
    types: "./dist/icons/phosphor-regular.d.ts",
    import: "./dist/icons/phosphor-regular.js",
  };

  return {
    ...packageJson,
    exports: exportsMap,
  };
}

function sectionRowsByName(rows = []) {
  return new Map(rows.map((row) => [row.name, row]));
}

function renderTable(headers, rows) {
  const heading = `| ${headers.join(" | ")} |`;
  const divider = `|${headers.map(() => "---").join("|")}|`;
  const body = rows
    .map((row) => `| ${headers.map((header) => row[header] ?? "").join(" | ")} |`)
    .join("\n");

  return [heading, divider, body].filter(Boolean).join("\n");
}

function renderSection(heading, table, afterMarkdown) {
  const lines = [`## ${heading}`, "", table];

  if (afterMarkdown?.trim()) {
    lines.push("", afterMarkdown.trim());
  }

  return lines.join("\n");
}

function formatPropertyRow(row, extractedProperty) {
  const typeValue = extractedProperty?.declaredType ?? row.type ?? "string";
  const defaultValue =
    extractedProperty?.defaultValue !== null && extractedProperty?.defaultValue !== undefined
      ? formatLiteral(extractedProperty.defaultValue)
      : row.defaultValue ?? "`undefined`";

  return {
    Name: `\`${row.name}\``,
    Type: row.type ?? `\`${typeValue}\``,
    Default: defaultValue,
    Description: row.description,
  };
}

function renderApiBlock(component) {
  const metadata = apiMetadata[component.tagName];
  const sourceText = componentSourceText(component);
  const extractedProperties = extractStaticProperties(sourceText);
  const extractedPropertiesByName = new Map(
    extractedProperties.map((property) => [property.name, property]),
  );
  const blockSections = [];

  if (metadata?.properties?.rows?.length) {
    const rows = metadata.properties.rows.map((row) =>
      formatPropertyRow(row, extractedPropertiesByName.get(row.name)),
    );
    blockSections.push(
      renderSection(
        "Properties",
        renderTable(["Name", "Type", "Default", "Description"], rows),
        metadata.properties.after,
      ),
    );
  }

  if (metadata?.slots?.rows?.length) {
    blockSections.push(
      renderSection(
        "Slots",
        renderTable(
          ["Name", "Description"],
          metadata.slots.rows.map((row) => ({
            Name: row.name === "default" ? "(default)" : `\`${row.name}\``,
            Description: row.description,
          })),
        ),
        metadata.slots.after,
      ),
    );
  }

  if (metadata?.events?.rows?.length) {
    blockSections.push(
      renderSection(
        "Events",
        renderTable(
          ["Name", "Detail", "Description"],
          metadata.events.rows.map((row) => ({
            Name: `\`${row.name}\``,
            Detail: row.detail,
            Description: row.description,
          })),
        ),
        metadata.events.after,
      ),
    );
  }

  if (metadata?.cssProperties?.rows?.length) {
    blockSections.push(
      renderSection(
        "CSS custom properties",
        renderTable(
          ["Name", "Default", "Description"],
          metadata.cssProperties.rows.map((row) => ({
            Name: `\`${row.name}\``,
            Default: row.default,
            Description: row.description,
          })),
        ),
        metadata.cssProperties.after,
      ),
    );
  }

  if (metadata?.shadowParts?.rows?.length) {
    blockSections.push(
      renderSection(
        "Shadow parts",
        renderTable(
          ["Name", "Description"],
          metadata.shadowParts.rows.map((row) => ({
            Name: `\`${row.name}\``,
            Description: row.description,
          })),
        ),
        metadata.shadowParts.after,
      ),
    );
  }

  if (blockSections.length === 0) {
    return "";
  }

  return `${API_START}\n${blockSections.join("\n\n")}\n${API_END}`;
}

function replaceDocApiBlock(fileText, component) {
  const generatedBlock = renderApiBlock(component);

  if (!generatedBlock) {
    return fileText;
  }

  if (fileText.includes(API_START) && fileText.includes(API_END)) {
    return fileText.replace(
      new RegExp(`${API_START}[\\s\\S]*?${API_END}`),
      generatedBlock,
    );
  }

  const nextContentMatch = fileText.match(/\n## (?:Accessibility|Best practices|Content guidelines|Public contract|Behavior|Methods)/);
  const insertionMatch =
    fileText.match(/\n## Usage/) ??
    fileText.match(/\n## Examples/) ??
    nextContentMatch;

  if (!insertionMatch) {
    throw new Error(`Could not find API insertion point for ${component.tagName}`);
  }

  let startIndex = insertionMatch.index + insertionMatch[0].length;

  if (insertionMatch[0].includes("Usage") || insertionMatch[0].includes("Examples")) {
    const postHeading = fileText.slice(startIndex);
    const nextHeadingOffset = postHeading.search(/\n## /);
    if (nextHeadingOffset === -1) {
      throw new Error(`Could not find section boundary after ${component.tagName}`);
    }
    startIndex += nextHeadingOffset;
  }

  const endMatch = fileText
    .slice(startIndex)
    .match(/\n## (?:Accessibility|Best practices|Content guidelines|Public contract|Behavior|Methods|Known limitations)/);
  const endIndex = endMatch ? startIndex + endMatch.index : fileText.length;

  return `${fileText.slice(0, startIndex).trimEnd()}\n\n${generatedBlock}\n\n${fileText
    .slice(endIndex)
    .trimStart()}`;
}

function generateStorybookArgTypes() {
  const blocks = standaloneDocComponents.map((component) => {
    const metadata = apiMetadata[component.tagName];
    const extractedProperties = extractStaticProperties(componentSourceText(component))
      .filter((property) => !property.internal)
      .map((property) => {
        const row = metadata?.properties?.rows?.find(
          (candidate) => kebabToCamel(candidate.name) === property.name,
        );

        if (!row || row.storybook === false) return null;

        return {
          ...property,
          row,
        };
      })
      .filter(Boolean);

    const argTypes = extractedProperties
      .map((property) => {
        const control =
          property.row?.control ??
          inferStorybookControl(property.row?.type ?? property.declaredType);
        const options = control.options
          ? `, options: ${JSON.stringify(control.options)}`
          : "";

        return `    ${JSON.stringify(property.name)}: { control: ${JSON.stringify(control.control)}${options} },`;
      })
      .join("\n");
    const args = extractedProperties
      .map((property) => {
        if (property.defaultValue === undefined) {
          return `    ${JSON.stringify(property.name)}: undefined,`;
        }

        return `    ${JSON.stringify(property.name)}: ${JSON.stringify(property.defaultValue)},`;
      })
      .join("\n");

    return `  ${JSON.stringify(component.tagName)}: {
    argTypes: {
${argTypes}
    },
    args: {
${args}
    },
  },`;
  });

  return `// ${GENERATED_HEADER}
export const componentStoryApi = {
${blocks.join("\n")}
} as const;

export function getComponentArgTypes(tagName: keyof typeof componentStoryApi) {
  return componentStoryApi[tagName].argTypes;
}

export function getComponentArgs(tagName: keyof typeof componentStoryApi) {
  return componentStoryApi[tagName].args;
}
`;
}

function writeGeneratedFiles() {
  ensureDir(registerRoot);

  writeText(packageComponentsIndexPath, generateComponentsIndexTs());
  writeText(path.join(registerRoot, "register-all.ts"), generateRegisterAllFile());

  for (const component of registerExportComponents) {
    writeText(
      path.join(registerRoot, component.sourceFile),
      generateRegisterFile(component),
    );
  }

  writeText(tsupConfigPath, generateTsupConfig());
  writeText(storybookGeneratedPath, generateStorybookArgTypes());
  writeText(docsNavGeneratedPath, generateDocsNavigation());
  writeText(docsComponentsIndexPath, generateComponentsIndex());

  const packageJson = JSON.parse(fs.readFileSync(componentsPackagePath, "utf8"));
  fs.writeFileSync(
    componentsPackagePath,
    `${JSON.stringify(generatePackageExports(packageJson), null, 2)}\n`,
  );

  for (const component of standaloneDocComponents) {
    const docsPath = docsPathFor(component);
    const text = fs.readFileSync(docsPath, "utf8");
    fs.writeFileSync(docsPath, replaceDocApiBlock(text, component));
  }
}

writeGeneratedFiles();
