// This file is generated by `npm run sync:components`.
import "./global.js";

// --- Component classes ---
export { FdButton } from "./components/fd-button.js";
export { FdButtonGroup } from "./components/fd-button-group.js";
export { FdCheckbox } from "./components/fd-checkbox.js";
export { FdCheckboxGroup } from "./components/fd-checkbox-group.js";
export { FdField } from "./components/fd-field.js";
export { FdIcon } from "./components/fd-icon.js";
export { FdInput } from "./components/fd-input.js";
export { FdLabel } from "./components/fd-label.js";
export { FdMenu } from "./components/fd-menu.js";
export { FdMenuItem } from "./components/fd-menu-item.js";
export { FdMessage } from "./components/fd-message.js";
export { FdOption } from "./components/fd-option.js";
export { FdRadio } from "./components/fd-radio.js";
export { FdRadioGroup } from "./components/fd-radio-group.js";
export { FdSelector } from "./components/fd-selector.js";
export { FdSplitButton } from "./components/fd-split-button.js";
export { FdFileInput } from "./components/fd-file-input.js";
export { FdSlider } from "./components/fd-slider.js";
export { FdBadge } from "./components/fd-badge.js";
export { FdBadgeGroup } from "./components/fd-badge-group.js";
export { FdChip } from "./components/fd-chip.js";
export { FdChipGroup } from "./components/fd-chip-group.js";
export { FdTextarea } from "./components/fd-textarea.js";
export { FdVisual } from "./components/fd-visual.js";
export { FdAlert } from "./components/fd-alert.js";
export { FdStripe } from "./components/fd-stripe.js";
export { FdLink } from "./components/fd-link.js";

// --- Public types ---
export type { ButtonVariant } from "./components/fd-button.js";
export type { ButtonGroupAlign, ButtonGroupDirection } from "./components/fd-button-group.js";
export type { CheckboxGroupOrientation } from "./components/fd-checkbox-group.js";
export type { InputType } from "./components/fd-input.js";
export type { MenuItemVariant } from "./components/fd-menu-item.js";
export type { MessageState, LiveMode } from "./components/fd-message.js";
export type { RadioGroupOrientation } from "./components/fd-radio-group.js";
export type { SelectorVariant } from "./components/fd-selector.js";
export type { FileInputItem, FileInputItemState, FileInputRejectReason, FileInputRejectedFile, FdFileInputChangeDetail, FdFileInputActionDetail } from "./components/fd-file-input.js";
export type { BadgeType } from "./components/fd-badge.js";
export type { ChipType } from "./components/fd-chip.js";
export type { VisualSize, VisualType } from "./components/fd-visual.js";
export type { AlertVariant, AlertType, AlertLive } from "./components/fd-alert.js";
export type { StripeType } from "./components/fd-stripe.js";
export type { LinkVariant, LinkSize } from "./components/fd-link.js";
export type { Placement } from "./components/placement.js";
export type {
  FdActionDetail,
  FdCheckboxGroupChangeDetail,
  FdMenuItemSelectDetail,
  FdMenuOpenChangeDetail,
  FdOpenChangeDetail,
  FdRadioGroupChangeDetail,
  FdSelectorChangeDetail,
  FdSelectorOpenChangeDetail,
  FdSplitButtonActionDetail,
  FdSplitButtonOpenChangeDetail,
  FdValueChangeDetail,
  FdValuesChangeDetail,
} from "./public-events.js";

// --- Icon registry ---
export { iconRegistry } from "./icons/registry.js";
