// This file is generated by `npm run sync:components`.
import "./global.js";

// --- Component classes ---
export { FdButton } from "./components/fd-button.js";
export { FdButtonGroup } from "./components/fd-button-group.js";
export { FdCheckbox } from "./components/fd-checkbox.js";
export { FdCheckboxGroup } from "./components/fd-checkbox-group.js";
export { FdField } from "./components/fd-field.js";
export { FdIcon } from "./components/fd-icon.js";
export { FdInput } from "./components/fd-input.js";
export { FdLabel } from "./components/fd-label.js";
export { FdMenu } from "./components/fd-menu.js";
export { FdMenuItem } from "./components/fd-menu-item.js";
export { FdMessage } from "./components/fd-message.js";
export { FdOption } from "./components/fd-option.js";
export { FdRadio } from "./components/fd-radio.js";
export { FdRadioGroup } from "./components/fd-radio-group.js";
export { FdSelector } from "./components/fd-selector.js";
export { FdSplitButton } from "./components/fd-split-button.js";
export { FdFileInput } from "./components/fd-file-input.js";
export { FdSlider } from "./components/fd-slider.js";
export { FdBadge } from "./components/fd-badge.js";
export { FdBadgeGroup } from "./components/fd-badge-group.js";
export { FdChip } from "./components/fd-chip.js";
export { FdChipGroup } from "./components/fd-chip-group.js";
export { FdTextarea } from "./components/fd-textarea.js";
export { FdVisual } from "./components/fd-visual.js";
export { FdAlert } from "./components/fd-alert.js";
export { FdStripe } from "./components/fd-stripe.js";
export { FdLink } from "./components/fd-link.js";
export { FdPagination } from "./components/fd-pagination.js";
export { FdGlobalHeader } from "./components/fd-global-header.js";
export { FdHeaderSearch } from "./components/fd-header-search.js";
export { FdDrawer } from "./components/fd-drawer.js";
export { FdPageHeader } from "./components/fd-page-header.js";
export { FdPageHeaderButton } from "./components/fd-page-header-button.js";
export { FdHero } from "./components/fd-hero.js";
export { FdPageFeedback } from "./components/fd-page-feedback.js";
export { FdEvent } from "./components/fd-event.js";
export { FdEventList } from "./components/fd-event-list.js";
export { FdTile } from "./components/fd-tile.js";
export { FdTileList } from "./components/fd-tile-list.js";
export { FdCard } from "./components/fd-card.js";

// --- Public types ---
export type { ButtonVariant } from "./components/fd-button.js";
export type { ButtonGroupAlign, ButtonGroupDirection } from "./components/fd-button-group.js";
export type { CheckboxGroupOrientation } from "./components/fd-checkbox-group.js";
export type { InputType } from "./components/fd-input.js";
export type { MenuItemVariant } from "./components/fd-menu-item.js";
export type { MessageState, LiveMode } from "./components/fd-message.js";
export type { RadioGroupOrientation } from "./components/fd-radio-group.js";
export type { SelectorVariant } from "./components/fd-selector.js";
export type { FileInputItem, FileInputItemState, FileInputRejectReason, FileInputRejectedFile, FdFileInputChangeDetail, FdFileInputActionDetail } from "./components/fd-file-input.js";
export type { BadgeType } from "./components/fd-badge.js";
export type { ChipType } from "./components/fd-chip.js";
export type { VisualSize, VisualType } from "./components/fd-visual.js";
export type { AlertVariant, AlertType, AlertLive } from "./components/fd-alert.js";
export type { StripeType } from "./components/fd-stripe.js";
export type { LinkVariant, LinkSize } from "./components/fd-link.js";
export type { GlobalHeaderSearchSurface, FdGlobalHeaderLeafItem, FdGlobalHeaderSectionItem, FdGlobalHeaderSection, FdGlobalHeaderLinkItem, FdGlobalHeaderPanelItem, FdGlobalHeaderNavigationItem, FdGlobalHeaderSearchConfig, FdGlobalHeaderSearchSubmitDetail } from "./components/fd-global-header.js";
export type { HeaderSearchSurface, FdHeaderSearchItem, FdHeaderSearchInputDetail, FdHeaderSearchOpenChangeDetail, FdHeaderSearchSubmitDetail, FdHeaderSearchActivateDetail } from "./components/fd-header-search.js";
export type { FdDrawerPlacement, FdDrawerCloseRequestDetail } from "./components/fd-drawer.js";
export type { FdPageHeaderBreadcrumb } from "./components/fd-page-header.js";
export type { HeroTone } from "./components/fd-hero.js";
export type { PageFeedbackView, PageFeedbackViewChangeReason, PageFeedbackViewChangeDetail, PageFeedbackReportSubmitDetail } from "./components/fd-page-feedback.js";
export type { EventTone } from "./components/fd-event.js";
export type { TileTone, FdTileLinkItem } from "./components/fd-tile.js";
export type { Placement } from "./components/placement.js";
export type {
  FdActionDetail,
  FdCheckboxGroupChangeDetail,
  FdMenuItemSelectDetail,
  FdMenuOpenChangeDetail,
  FdOpenChangeDetail,
  FdRadioGroupChangeDetail,
  FdSelectorChangeDetail,
  FdSelectorOpenChangeDetail,
  FdSplitButtonActionDetail,
  FdSplitButtonOpenChangeDetail,
  FdValueChangeDetail,
  FdValuesChangeDetail,
} from "./public-events.js";

export { createFdGlobalHeaderContent, createFdGlobalHeaderSearchConfig, createHeaderSearchItemsFromNavigation } from "./fd-global-header-content.js";
export type { FdGlobalHeaderContent, FdGlobalHeaderContentAdapter } from "./fd-global-header-content.js";

// --- Icon registry ---
export { iconRegistry } from "./icons/registry.js";
