// This file is generated by `npm run sync:components`.
import { FdAlert } from "../components/fd-alert.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-alert")) {
  customElements.define("fd-alert", FdAlert);
}
