// This file is generated by `npm run sync:components`.
import { FdBadge } from "../components/fd-badge.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-badge")) {
  customElements.define("fd-badge", FdBadge);
}
