// This file is generated by `npm run sync:components`.
import { FdButtonGroup } from "../components/fd-button-group.js";

if (!customElements.get("fd-button-group")) {
  customElements.define("fd-button-group", FdButtonGroup);
}
