// This file is generated by `npm run sync:components`.
import { FdBadgeGroup } from "../components/fd-badge-group.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-badge-group")) {
  customElements.define("fd-badge-group", FdBadgeGroup);
}
