// This file is generated by `npm run sync:components`.
import { FdBadgeGroup } from "../components/fd-badge-group.js";

if (!customElements.get("fd-badge-group")) {
  customElements.define("fd-badge-group", FdBadgeGroup);
}
