// This file is generated by `npm run sync:components`.
import { FdCardGroup } from "../components/fd-card-group.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-card-group")) {
  customElements.define("fd-card-group", FdCardGroup);
}
