// This file is generated by `npm run sync:components`.
import { FdChipGroup } from "../components/fd-chip-group.js";

if (!customElements.get("fd-chip-group")) {
  customElements.define("fd-chip-group", FdChipGroup);
}
