// This file is generated by `npm run sync:components`.
import { FdCardGroup } from "../components/fd-card-group.js";

if (!customElements.get("fd-card-group")) {
  customElements.define("fd-card-group", FdCardGroup);
}
