// This file is generated by `npm run sync:components`.
import { FdChip } from "../components/fd-chip.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-chip")) {
  customElements.define("fd-chip", FdChip);
}
