// This file is generated by `npm run sync:components`.
import { FdCheckboxGroup } from "../components/fd-checkbox-group.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdCheckbox } from "../components/fd-checkbox.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-checkbox")) {
  customElements.define("fd-checkbox", FdCheckbox);
}

if (!customElements.get("fd-checkbox-group")) {
  customElements.define("fd-checkbox-group", FdCheckboxGroup);
}
