// This file is generated by `npm run sync:components`.
import { FdCard } from "../components/fd-card.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-card")) {
  customElements.define("fd-card", FdCard);
}
