// This file is generated by `npm run sync:components`.
import { FdConfirmationRecord } from "../components/fd-confirmation-record.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-confirmation-record")) {
  customElements.define("fd-confirmation-record", FdConfirmationRecord);
}
