// This file is generated by `npm run sync:components`.
import { FdDrawer } from "../components/fd-drawer.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-drawer")) {
  customElements.define("fd-drawer", FdDrawer);
}
