// This file is generated by `npm run sync:components`.
import { FdEventList } from "../components/fd-event-list.js";

if (!customElements.get("fd-event-list")) {
  customElements.define("fd-event-list", FdEventList);
}
