// This file is generated by `npm run sync:components`.
import { FdEvent } from "../components/fd-event.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-event")) {
  customElements.define("fd-event", FdEvent);
}
