// This file is generated by `npm run sync:components`.
import { FdErrorSummary } from "../components/fd-error-summary.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-error-summary")) {
  customElements.define("fd-error-summary", FdErrorSummary);
}
