// This file is generated by `npm run sync:components`.
import { FdFileInput } from "../components/fd-file-input.js";

if (!customElements.get("fd-file-input")) {
  customElements.define("fd-file-input", FdFileInput);
}
