// This file is generated by `npm run sync:components`.
import { FdFormField } from "../components/fd-form-field.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-form-field")) {
  customElements.define("fd-form-field", FdFormField);
}
