// This file is generated by `npm run sync:components`.
import { FdField } from "../components/fd-field.js";
import { FdLabel } from "../components/fd-label.js";
import { FdInput } from "../components/fd-input.js";
import { FdMessage } from "../components/fd-message.js";

if (!customElements.get("fd-label")) {
  customElements.define("fd-label", FdLabel);
}

if (!customElements.get("fd-input")) {
  customElements.define("fd-input", FdInput);
}

if (!customElements.get("fd-message")) {
  customElements.define("fd-message", FdMessage);
}

if (!customElements.get("fd-field")) {
  customElements.define("fd-field", FdField);
}
