// This file is generated by `npm run sync:components`.
import { FdGlobalHeader } from "../components/fd-global-header.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdIcon } from "../components/fd-icon.js";
import { FdHeaderSearch } from "../components/fd-header-search.js";
import { FdDrawer } from "../components/fd-drawer.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-header-search")) {
  customElements.define("fd-header-search", FdHeaderSearch);
}

if (!customElements.get("fd-drawer")) {
  customElements.define("fd-drawer", FdDrawer);
}

if (!customElements.get("fd-global-header")) {
  customElements.define("fd-global-header", FdGlobalHeader);
}
