// This file is generated by `npm run sync:components`.
import { FdGlobalHeader } from "../components/fd-global-header.js";
import { FdIcon } from "../components/fd-icon.js";
import { FdInput } from "../components/fd-input.js";

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-input")) {
  customElements.define("fd-input", FdInput);
}

if (!customElements.get("fd-global-header")) {
  customElements.define("fd-global-header", FdGlobalHeader);
}
