// This file is generated by `npm run sync:components`.
import { FdGlobalFooter } from "../components/fd-global-footer.js";

if (!customElements.get("fd-global-footer")) {
  customElements.define("fd-global-footer", FdGlobalFooter);
}
