// This file is generated by `npm run sync:components`.
import { FdHero } from "../components/fd-hero.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-hero")) {
  customElements.define("fd-hero", FdHero);
}
