// This file is generated by `npm run sync:components`.
import { FdHeaderSearch } from "../components/fd-header-search.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdIcon } from "../components/fd-icon.js";
import { FdButton } from "../components/fd-button.js";
import { FdDrawer } from "../components/fd-drawer.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-button")) {
  customElements.define("fd-button", FdButton);
}

if (!customElements.get("fd-drawer")) {
  customElements.define("fd-drawer", FdDrawer);
}

if (!customElements.get("fd-header-search")) {
  customElements.define("fd-header-search", FdHeaderSearch);
}
