// This file is generated by `npm run sync:components`.
import { FdInput } from "../components/fd-input.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-input")) {
  customElements.define("fd-input", FdInput);
}
