// This file is generated by `npm run sync:components`.
import { FdInfotip } from "../components/fd-infotip.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-infotip")) {
  customElements.define("fd-infotip", FdInfotip);
}
