// This file is generated by `npm run sync:components`.
import { FdIcon } from "../components/fd-icon.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}
