// This file is generated by `npm run sync:components`.
import { FdLink } from "../components/fd-link.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-link")) {
  customElements.define("fd-link", FdLink);
}
