// This file is generated by `npm run sync:components`.
import { FdLabel } from "../components/fd-label.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-label")) {
  customElements.define("fd-label", FdLabel);
}
