// This file is generated by `npm run sync:components`.
import { FdLinkCategory } from "../components/fd-link-category.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdIcon } from "../components/fd-icon.js";
import { FdVisual } from "../components/fd-visual.js";
import { FdStripe } from "../components/fd-stripe.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-visual")) {
  customElements.define("fd-visual", FdVisual);
}

if (!customElements.get("fd-stripe")) {
  customElements.define("fd-stripe", FdStripe);
}

if (!customElements.get("fd-link-category")) {
  customElements.define("fd-link-category", FdLinkCategory);
}
