// This file is generated by `npm run sync:components`.
import { FdMenu } from "../components/fd-menu.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdMenuItem } from "../components/fd-menu-item.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-menu-item")) {
  customElements.define("fd-menu-item", FdMenuItem);
}

if (!customElements.get("fd-menu")) {
  customElements.define("fd-menu", FdMenu);
}
