// This file is generated by `npm run sync:components`.
import { FdMessage } from "../components/fd-message.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-message")) {
  customElements.define("fd-message", FdMessage);
}
