// This file is generated by `npm run sync:components`.
import { FdMediaList } from "../components/fd-media-list.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-media-list")) {
  customElements.define("fd-media-list", FdMediaList);
}
