// This file is generated by `npm run sync:components`.
import { FdMediaItem } from "../components/fd-media-item.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-media-item")) {
  customElements.define("fd-media-item", FdMediaItem);
}
