// This file is generated by `npm run sync:components`.
import { FdOrgDetails } from "../components/fd-org-details.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdBadge } from "../components/fd-badge.js";
import { FdButton } from "../components/fd-button.js";
import { FdIcon } from "../components/fd-icon.js";
import { FdVisual } from "../components/fd-visual.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-badge")) {
  customElements.define("fd-badge", FdBadge);
}

if (!customElements.get("fd-button")) {
  customElements.define("fd-button", FdButton);
}

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-visual")) {
  customElements.define("fd-visual", FdVisual);
}

if (!customElements.get("fd-org-details")) {
  customElements.define("fd-org-details", FdOrgDetails);
}
