// This file is generated by `npm run sync:components`.
import { FdOrgOutline } from "../components/fd-org-outline.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdIcon } from "../components/fd-icon.js";
import { FdVisual } from "../components/fd-visual.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-visual")) {
  customElements.define("fd-visual", FdVisual);
}

if (!customElements.get("fd-org-outline")) {
  customElements.define("fd-org-outline", FdOrgOutline);
}
