// This file is generated by `npm run sync:components`.
import { FdPerson } from "../components/fd-person.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-person")) {
  customElements.define("fd-person", FdPerson);
}
