// This file is generated by `npm run sync:components`.
import { FdPagination } from "../components/fd-pagination.js";
import { FdIcon } from "../components/fd-icon.js";

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-pagination")) {
  customElements.define("fd-pagination", FdPagination);
}
