// This file is generated by `npm run sync:components`.
import { FdPageFeedback } from "../components/fd-page-feedback.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdButton } from "../components/fd-button.js";
import { FdButtonGroup } from "../components/fd-button-group.js";
import { FdLink } from "../components/fd-link.js";
import { FdLabel } from "../components/fd-label.js";
import { FdTextarea } from "../components/fd-textarea.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-button")) {
  customElements.define("fd-button", FdButton);
}

if (!customElements.get("fd-button-group")) {
  customElements.define("fd-button-group", FdButtonGroup);
}

if (!customElements.get("fd-link")) {
  customElements.define("fd-link", FdLink);
}

if (!customElements.get("fd-label")) {
  customElements.define("fd-label", FdLabel);
}

if (!customElements.get("fd-textarea")) {
  customElements.define("fd-textarea", FdTextarea);
}

if (!customElements.get("fd-page-feedback")) {
  customElements.define("fd-page-feedback", FdPageFeedback);
}
