// This file is generated by `npm run sync:components`.
import { FdPageHeader } from "../components/fd-page-header.js";
import { FdIcon } from "../components/fd-icon.js";
import { FdPageHeaderButton } from "../components/fd-page-header-button.js";

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-page-header-button")) {
  customElements.define("fd-page-header-button", FdPageHeaderButton);
}

if (!customElements.get("fd-page-header")) {
  customElements.define("fd-page-header", FdPageHeader);
}
