// This file is generated by `npm run sync:components`.
import { FdReviewList } from "../components/fd-review-list.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-review-list")) {
  customElements.define("fd-review-list", FdReviewList);
}
