// This file is generated by `npm run sync:components`.
import { FdRadioGroup } from "../components/fd-radio-group.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdRadio } from "../components/fd-radio.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-radio")) {
  customElements.define("fd-radio", FdRadio);
}

if (!customElements.get("fd-radio-group")) {
  customElements.define("fd-radio-group", FdRadioGroup);
}
