// This file is generated by `npm run sync:components`.
import { FdRadio } from "../components/fd-radio.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-radio")) {
  customElements.define("fd-radio", FdRadio);
}
