// This file is generated by `npm run sync:components`.
import { FdSidebarMenu } from "../components/fd-sidebar-menu.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdIcon } from "../components/fd-icon.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-icon")) {
  customElements.define("fd-icon", FdIcon);
}

if (!customElements.get("fd-sidebar-menu")) {
  customElements.define("fd-sidebar-menu", FdSidebarMenu);
}
