// This file is generated by `npm run sync:components`.
import { FdSelector } from "../components/fd-selector.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdOption } from "../components/fd-option.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-option")) {
  customElements.define("fd-option", FdOption);
}

if (!customElements.get("fd-selector")) {
  customElements.define("fd-selector", FdSelector);
}
