// This file is generated by `npm run sync:components`.
import { FdSocialMediaList } from "../components/fd-social-media-list.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-social-media-list")) {
  customElements.define("fd-social-media-list", FdSocialMediaList);
}
