// This file is generated by `npm run sync:components`.
import { FdSlider } from "../components/fd-slider.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-slider")) {
  customElements.define("fd-slider", FdSlider);
}
