// This file is generated by `npm run sync:components`.
import { FdSplitButton } from "../components/fd-split-button.js";
import { FdButton } from "../components/fd-button.js";
import { FdMenuItem } from "../components/fd-menu-item.js";
import { FdMenu } from "../components/fd-menu.js";

if (!customElements.get("fd-button")) {
  customElements.define("fd-button", FdButton);
}

if (!customElements.get("fd-menu-item")) {
  customElements.define("fd-menu-item", FdMenuItem);
}

if (!customElements.get("fd-menu")) {
  customElements.define("fd-menu", FdMenu);
}

if (!customElements.get("fd-split-button")) {
  customElements.define("fd-split-button", FdSplitButton);
}
