// This file is generated by `npm run sync:components`.
import { FdSocialMediaItem } from "../components/fd-social-media-item.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-social-media-item")) {
  customElements.define("fd-social-media-item", FdSocialMediaItem);
}
