// This file is generated by `npm run sync:components`.
import { FdSlider } from "../components/fd-slider.js";

if (!customElements.get("fd-slider")) {
  customElements.define("fd-slider", FdSlider);
}
