// This file is generated by `npm run sync:components`.
import { FdStripe } from "../components/fd-stripe.js";

if (!customElements.get("fd-stripe")) {
  customElements.define("fd-stripe", FdStripe);
}
