// This file is generated by `npm run sync:components`.
import { FdSidebarNav } from "../components/fd-sidebar-nav.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-sidebar-nav")) {
  customElements.define("fd-sidebar-nav", FdSidebarNav);
}
