// This file is generated by `npm run sync:components`.
import { FdTileList } from "../components/fd-tile-list.js";

if (!customElements.get("fd-tile-list")) {
  customElements.define("fd-tile-list", FdTileList);
}
