// This file is generated by `npm run sync:components`.
import { FdTextarea } from "../components/fd-textarea.js";

if (!customElements.get("fd-textarea")) {
  customElements.define("fd-textarea", FdTextarea);
}
