// This file is generated by `npm run sync:components`.
import { FdTextarea } from "../components/fd-textarea.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-textarea")) {
  customElements.define("fd-textarea", FdTextarea);
}
