// This file is generated by `npm run sync:components`.
import { FdTileList } from "../components/fd-tile-list.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-tile-list")) {
  customElements.define("fd-tile-list", FdTileList);
}
