// This file is generated by `npm run sync:components`.
import { FdTile } from "../components/fd-tile.js";
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import { FdVisual } from "../components/fd-visual.js";

warnIfDesignSystemRuntimeMissing();

if (!customElements.get("fd-visual")) {
  customElements.define("fd-visual", FdVisual);
}

if (!customElements.get("fd-tile")) {
  customElements.define("fd-tile", FdTile);
}
