/**
 * This file is generated by `npm run sync:components`.
 *
 * Convenience entry point — registers all public components and icons.
 *
 * Usage:
 * ```ts
 * import "@fdic-ds/components/register-all";
 * ```
 */
import "./fd-button.js";
import "./fd-button-group.js";
import "./fd-checkbox.js";
import "./fd-checkbox-group.js";
import "./fd-field.js";
import "./fd-icon.js";
import "./fd-input.js";
import "./fd-label.js";
import "./fd-menu.js";
import "./fd-message.js";
import "./fd-radio.js";
import "./fd-radio-group.js";
import "./fd-selector.js";
import "./fd-split-button.js";
import "./fd-file-input.js";
import "./fd-slider.js";
import "./fd-badge.js";
import "./fd-badge-group.js";
import "./fd-chip.js";
import "./fd-chip-group.js";
import "./fd-textarea.js";
import "./fd-visual.js";
import "./fd-alert.js";
import "./fd-stripe.js";
import "../icons/phosphor-regular.js";
