/**
 * This file is generated by `npm run sync:components`.
 *
 * Convenience entry point — registers all public components and icons.
 * Requires the shared token runtime stylesheet.
 *
 * Usage:
 * ```ts
 * import "@jflamb/fdic-ds-components/styles.css";
 * import "@jflamb/fdic-ds-components/register-all";
 * ```
 */
import { warnIfDesignSystemRuntimeMissing } from "../runtime.js";
import "./fd-button.js";
import "./fd-button-group.js";
import "./fd-checkbox.js";
import "./fd-checkbox-group.js";
import "./fd-field.js";
import "./fd-icon.js";
import "./fd-input.js";
import "./fd-label.js";
import "./fd-menu.js";
import "./fd-message.js";
import "./fd-radio.js";
import "./fd-radio-group.js";
import "./fd-selector.js";
import "./fd-split-button.js";
import "./fd-file-input.js";
import "./fd-slider.js";
import "./fd-badge.js";
import "./fd-badge-group.js";
import "./fd-chip.js";
import "./fd-chip-group.js";
import "./fd-textarea.js";
import "./fd-visual.js";
import "./fd-alert.js";
import "./fd-stripe.js";
import "./fd-link.js";
import "./fd-pagination.js";
import "./fd-global-header.js";
import "./fd-header-search.js";
import "./fd-drawer.js";
import "./fd-page-header.js";
import "./fd-hero.js";
import "./fd-page-feedback.js";
import "./fd-event.js";
import "./fd-event-list.js";
import "./fd-tile.js";
import "./fd-tile-list.js";
import "./fd-card.js";
import "./fd-global-footer.js";
import "./fd-card-group.js";
import "./fd-confirmation-record.js";
import "./fd-form-field.js";
import "./fd-error-summary.js";
import "./fd-review-list.js";
import "../icons/phosphor-regular.js";

warnIfDesignSystemRuntimeMissing();
