import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    // Root entry (side-effect-free)
    index: "src/index.ts",
    "public-events": "src/public-events.ts",

    // Public helper modules
    "fd-global-header-content": "src/fd-global-header-content.ts",
    "fd-global-header-drupal": "src/fd-global-header-drupal.ts",

    // Per-component symbol exports
    "components/fd-button": "src/components/fd-button.ts",
    "components/fd-button-group": "src/components/fd-button-group.ts",
    "components/fd-checkbox": "src/components/fd-checkbox.ts",
    "components/fd-checkbox-group": "src/components/fd-checkbox-group.ts",
    "components/fd-field": "src/components/fd-field.ts",
    "components/fd-icon": "src/components/fd-icon.ts",
    "components/fd-input": "src/components/fd-input.ts",
    "components/fd-label": "src/components/fd-label.ts",
    "components/fd-menu": "src/components/fd-menu.ts",
    "components/fd-menu-item": "src/components/fd-menu-item.ts",
    "components/fd-message": "src/components/fd-message.ts",
    "components/fd-option": "src/components/fd-option.ts",
    "components/fd-radio": "src/components/fd-radio.ts",
    "components/fd-radio-group": "src/components/fd-radio-group.ts",
    "components/fd-selector": "src/components/fd-selector.ts",
    "components/fd-split-button": "src/components/fd-split-button.ts",
    "components/fd-file-input": "src/components/fd-file-input.ts",
    "components/fd-slider": "src/components/fd-slider.ts",
    "components/fd-badge": "src/components/fd-badge.ts",
    "components/fd-badge-group": "src/components/fd-badge-group.ts",
    "components/fd-chip": "src/components/fd-chip.ts",
    "components/fd-chip-group": "src/components/fd-chip-group.ts",
    "components/fd-textarea": "src/components/fd-textarea.ts",
    "components/fd-visual": "src/components/fd-visual.ts",
    "components/fd-alert": "src/components/fd-alert.ts",
    "components/fd-stripe": "src/components/fd-stripe.ts",
    "components/fd-link": "src/components/fd-link.ts",
    "components/fd-pagination": "src/components/fd-pagination.ts",
    "components/fd-global-header": "src/components/fd-global-header.ts",
    "components/fd-header-search": "src/components/fd-header-search.ts",
    "components/fd-drawer": "src/components/fd-drawer.ts",
    "components/fd-page-header": "src/components/fd-page-header.ts",
    "components/fd-page-header-button": "src/components/fd-page-header-button.ts",
    "components/fd-hero": "src/components/fd-hero.ts",
    "components/fd-page-feedback": "src/components/fd-page-feedback.ts",
    "components/fd-event": "src/components/fd-event.ts",
    "components/fd-event-list": "src/components/fd-event-list.ts",
    "components/fd-tile": "src/components/fd-tile.ts",
    "components/fd-tile-list": "src/components/fd-tile-list.ts",
    "components/fd-card": "src/components/fd-card.ts",
    "components/fd-global-footer": "src/components/fd-global-footer.ts",
    "components/fd-card-group": "src/components/fd-card-group.ts",

    // Registration entry points
    "register/register-all": "src/register/register-all.ts",
    "register/fd-button": "src/register/fd-button.ts",
    "register/fd-button-group": "src/register/fd-button-group.ts",
    "register/fd-checkbox": "src/register/fd-checkbox.ts",
    "register/fd-checkbox-group": "src/register/fd-checkbox-group.ts",
    "register/fd-field": "src/register/fd-field.ts",
    "register/fd-icon": "src/register/fd-icon.ts",
    "register/fd-input": "src/register/fd-input.ts",
    "register/fd-label": "src/register/fd-label.ts",
    "register/fd-menu": "src/register/fd-menu.ts",
    "register/fd-message": "src/register/fd-message.ts",
    "register/fd-radio": "src/register/fd-radio.ts",
    "register/fd-radio-group": "src/register/fd-radio-group.ts",
    "register/fd-selector": "src/register/fd-selector.ts",
    "register/fd-split-button": "src/register/fd-split-button.ts",
    "register/fd-file-input": "src/register/fd-file-input.ts",
    "register/fd-slider": "src/register/fd-slider.ts",
    "register/fd-badge": "src/register/fd-badge.ts",
    "register/fd-badge-group": "src/register/fd-badge-group.ts",
    "register/fd-chip": "src/register/fd-chip.ts",
    "register/fd-chip-group": "src/register/fd-chip-group.ts",
    "register/fd-textarea": "src/register/fd-textarea.ts",
    "register/fd-visual": "src/register/fd-visual.ts",
    "register/fd-alert": "src/register/fd-alert.ts",
    "register/fd-stripe": "src/register/fd-stripe.ts",
    "register/fd-link": "src/register/fd-link.ts",
    "register/fd-pagination": "src/register/fd-pagination.ts",
    "register/fd-global-header": "src/register/fd-global-header.ts",
    "register/fd-header-search": "src/register/fd-header-search.ts",
    "register/fd-drawer": "src/register/fd-drawer.ts",
    "register/fd-page-header": "src/register/fd-page-header.ts",
    "register/fd-hero": "src/register/fd-hero.ts",
    "register/fd-page-feedback": "src/register/fd-page-feedback.ts",
    "register/fd-event": "src/register/fd-event.ts",
    "register/fd-event-list": "src/register/fd-event-list.ts",
    "register/fd-tile": "src/register/fd-tile.ts",
    "register/fd-tile-list": "src/register/fd-tile-list.ts",
    "register/fd-card": "src/register/fd-card.ts",
    "register/fd-global-footer": "src/register/fd-global-footer.ts",
    "register/fd-card-group": "src/register/fd-card-group.ts",

    // Icon packs
    "icons/phosphor-regular": "src/icons/phosphor-regular.ts",
  },
  format: ["esm"],
  dts: true,
  clean: true,
  splitting: true,
});
