// This file is generated by `npm run sync:components`.
export const reactPackageStatus = "experimental-generated-wrappers";

export { FdButton } from "./generated/fd-button.js";
export type { FdButtonProps } from "./generated/fd-button.js";
export { FdInput } from "./generated/fd-input.js";
export type { FdInputProps } from "./generated/fd-input.js";
export { FdAlert } from "./generated/fd-alert.js";
export type { FdAlertProps } from "./generated/fd-alert.js";
